language: scala
scala: 2.12.3
jdk: oraclejdk8

sudo: required
dist: trusty

addons:
  apt:
    packages:
    - bc

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport codacyCoverage