sudo: required

dist: trusty

language: scala

addons:
  apt:
    packages:
    - bc

scala:
  - 2.11.8
jdk:
  - oraclejdk8
  
script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport codacyCoverage