sudo: required

dist: trusty

language: scala

addons:
  apt:
    packages:
    - bc

scala:
  - 2.11.7
jdk:
  - oraclejdk8
  
after_script:
  - sbt coverage test
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage