dist: xenial

jdk:
  - oraclejdk8
  - oraclejdk11
  - openjdk8
  - openjdk11

language: scala
scala:
  - 2.12.7
  - 2.13.0-M5

addons:
  apt:
    packages:
    - bc

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport codacyCoverage