dist: xenial

jdk:
  - oraclejdk11
  - oraclejdk13
  - openjdk11
  - openjdk13

language: scala
scala:
  - 2.13.1

addons:
  apt:
    packages:
    - bc

script:
  - sbt clean coverage test

after_success:
  - sbt coverageReport codacyCoverage